### ISSUE TITLE
Öğrenci İşleri Örnek Raporları

### ISSUE THREAD

**Issue by anndro** [zetaops/ulakbus#109]
Asagidaki 3 rapor ornek olarak belirlenmistir:

Öğrenci istatistikleri:
- Birim bazlı öğrenci sayıları,(Fakülte/Bölüm)
- Yaşa, Cinsiyete ve Doğumyerine göre öğrenci sayıları,

Harç Durumu;
- Birim bazlı harç ödeyen öğrenci sayısı,
- Birim bazlı harç ödemeyen öğrenci sayısı,
- Birim bazlı toplam ödenen ve ödenmesi gereken harç tutarları

Ders Sınav Bilgileri;
- Dönem bazlı olarak, aktif ve pasif dersler için aşağıadki bilgiler listelenecektir,
- Fakülte, Bölüm, Ders No, Ders Adı, Şube, Sınav Tipi(Vize/Final vs.), Sınav Katkısı, Sınav tarihi, Sınav durumu(Notlar Yayınlanmış, henüz yapılmamış, değerlendir aşamasında vs.), Yayınlanma Tarihi, Ders Sorumlusu

**Comment by alirizakeles** [comment]
Done
