### ISSUE TITLE
login yapan kullanicinin rollerini alabilecegimiz bir api path.

### ISSUE THREAD

**Issue by ghost** [zetaops/ulakbus#117]
giris yapan kullaniciya gore degisecek olan dashboard birimleri olacagindan ve dashboard'da kullanicinin o anki rolu belirtileceginden ui'in bunu alabilecegi bir path gerekli.

**Comment by alirizakeles** [comment]
Bu bilgiler response objesine current_user olarak eklendi. 
Done!
