### ISSUE TITLE
kadro workflowu farkli degerler donuyor

### ISSUE THREAD

**Issue by ghost** [zetaops/ulakbus#119]
![screen shot 2015-12-18 at 15 38 14](https://cloud.githubusercontent.com/assets/765734/11898063/a33d20e8-a59d-11e5-876a-17f826ea9d4b.png)
![screen shot 2015-12-18 at 15 40 30](https://cloud.githubusercontent.com/assets/765734/11898072/b4b4d37a-a59d-11e5-8317-b80f25ad299f.png)
![screen shot 2015-12-18 at 15 40 59](https://cloud.githubusercontent.com/assets/765734/11898077/c716a57a-a59d-11e5-9488-1070752c23d8.png)

**Comment by alirizakeles** [comment]
Riak 2.1.2 upgrade sonrasi test edilecek.

**Comment by alirizakeles** [comment]
Tamamlandi.
