### ISSUE TITLE
Program ekranında bağlı alanlarda value yerine key görülüyor

### ISSUE THREAD

**Issue by kunthar** [zetaops/ulakbus#126]
Undefined olan alan dışında, key görülen alanlar ektedir.

<img width="1269" alt="screen shot 2015-12-24 at 3 57 07 pm" src="https://cloud.githubusercontent.com/assets/49767/11998149/19679630-aa9a-11e5-8f58-6121f06d3f4a.png">

**Comment by alirizakeles** [comment]
Bu bir yetkilendirme problemi. 
zetaops/zengine#23 ile cozulecek.
