### ISSUE TITLE
Başarıyla sonlanmıştır ne demek ?

### ISSUE THREAD

**Issue by mahmutelmas06** [zetaops/ulakbus#299]
Yani proje tamamen askıya kaldırıldı ve kullanılmıyor mu ?

Yoksa şu anda tüm kurumlar ulakbus mü kullanıyor ?

**Comment by kunthar** [comment]
Proje, istenen testlerden başarıyla geçerek TÜBİTAK ULAKBİM kurumuna teslim edilmiştir. Bundan sonraki akibetini kendileriyle görüşerek öğrenebilirsiniz.
