### ISSUE TITLE
Ayni modele verilen linklerin farkli verbose_name ozelliklerine sahip olabilmesi

### ISSUE THREAD

**Issue by alirizakeles** [zetaops/ulakbus#47]
Su ornekte oldugu gibi iki farkli field ayni modele baglanabiliyor:
https://github.com/zetaops/ulakbus/blob/master/ulakbus/models/hitap.py#L426

Bu on yuzde ayri fieldlarin ayni isimle gorunmesine yol aciyor. 

Bunlara fieldlar gibi verbose_name verebilmeliyiz. Sunun gibi:

```
    ...
    telefon = field.String("Telefon", index=True)
    personel = Personel() # personelin kendisi
    vekil = Personel("Vekil") # izin durumunda vekili
    ...

```

ya da baska bir bicimde.

**Comment by evrenesat** [comment]
FIXED
