### ISSUE TITLE
Manage.py icin belgelendirme

### ISSUE THREAD

**Issue by alirizakeles** [zetaops/ulakbus#53]
Manage.py'in nasil kullanilacagi ile ilgili bir dokuman hazirlayip ulakbus.org belgelerine eklememiz gerek.

**Comment by fjzach** [comment]
https://github.com/zetaops/ulakbus.org/blob/master/source/manage.py_bilgilendirme.rst

**Comment by alirizakeles** [comment]
Cok komut eklendi. Belgeyi bastan yazmaliyiz.
