### ISSUE TITLE
Ogrenci Modeli Iliskilerinin Duzenlenmesi ve Iyilestirilmesi

### ISSUE THREAD

**Issue by alirizakeles** [zetaops/ulakbus#57]

**Comment by alirizakeles** [comment]
surada calismaya basladik: https://github.com/zetaops/ulakbus.org/commit/d934bf3b93f2187a38c99343b1dda98738d189ba?diff=split

**Comment by fjzach** [comment]
modellerin içerikleri geliştirildi
