### ISSUE TITLE
Ulakbus menu view kisminin test edilmesi

### ISSUE THREAD

**Issue by yetercatikkas** [zetaops/ulakbus#89]

**Comment by alirizakeles** [comment]
76f12817ed2456ae7757d6c92ead45bc3d9f1e4a, 1a7121354eeef4a4eeecac0edc09796e85cf3a8a, 0750d02937cde809b5a675108b4fe0f0abccc41a, d6b3b61be0930600c0efcb0671272522146503cf

ile eklendi. 

Done
