### ISSUE TITLE
AuthBackend kullanıcı oturumunu Role id'si ile yapıyor.

### ISSUE THREAD

**Issue by evrenesat** [zetaops/ulakbus#92]
Mevcut halde, hem kimlik  hem de izin yönetimini Role nesnesi uzerinde yapıyoruz. Kullanıcının çıkış yapmadan rol değiştirebilmesi için bu iki ayrılmalı ve oturum user idsine bağlanmalı.

**Comment by alirizakeles** [comment]
Tamamlandi.
